import { Lexend_Deca, Google_Sans_Code } from "next/font/google";
import "./globals.css";

const lexendDeca = Lexend_Deca({
	weight: ["400", "500", "700"],
	subsets: ["latin"],
	variable: "--font-lexendeca",
});

export const metadata = {
	title: "Happy Birthday, Shinta 🤍",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${lexendDeca.variable} antialiased`}>{children}</body>
		</html>
	);
}
